#!/usr/bin/env python3

import asyncio

from hydra.client import Client
from hydra.core.common.init import *


async def main():
    main_object = await init(Client)
    await run(main_object)

asyncio.run(main())
