#!/usr/bin/env python3

import asyncio

from hydra.supervisor import Supervisor
from hydra.core.common.init import *

async def main():
    main_object = await init(Supervisor)
    await run(main_object)

asyncio.run(main())

