#!/usr/bin/env python3

import asyncio
import logging

from hydra.supervisor import Supervisor
from hydra.core.common.init import *

logging.basicConfig(level=logging.DEBUG)

async def main():
    main_object = await init(Supervisor)
    await run(main_object)

asyncio.run(main())

